import { getUnit, saveUnit, getVocabularySets, speakingOptions, makeId, yearLabel } from "./store.js";
const q=s=>document.querySelector(s), form=q("#unit-form"), list=q("#lessons"), status=q("#status"), requested=new URLSearchParams(location.search).get("unit");
const vocab=await getVocabularySets(); let unit=requested?await getUnit(requested):null; let lessons=unit?.lessons?.map(x=>({...x}))||[];
q("#year").innerHTML=[0,1,2,3,4,5,6].map(y=>`<option value="${y}">${yearLabel(y)}</option>`).join(""); if(unit){q("#page-title").textContent="Edit unit";q("#year").value=unit.yearLevel;q("#english").value=unit.englishTitle;q("#chinese").value=unit.chineseTitle||"";}
const esc=(v="")=>{const d=document.createElement("div");d.textContent=v;return d.innerHTML;};
function render(){list.innerHTML=lessons.map((l,i)=>`<article class="lesson-editor" data-index="${i}"><div class="lesson-top"><span class="lesson-number">${i+1}</span><label class="title-field"><span>Lesson title</span><input data-field="title" value="${esc(l.title)}" maxlength="120"></label><div class="reorder"><button type="button" data-up aria-label="Move lesson up" ${i===0?"disabled":""}>↑</button><button type="button" data-down aria-label="Move lesson down" ${i===lessons.length-1?"disabled":""}>↓</button></div></div><div class="lesson-fields"><label>Learning intention<textarea data-field="learningIntention" rows="2">${esc(l.learningIntention)}</textarea></label><label>Vocabulary<select data-field="vocabularySetId"><option value="">None</option>${vocab.map(v=>`<option value="${v.id}" ${v.id===l.vocabularySetId?"selected":""}>${esc(v.title)} · ${v.items.length} items</option>`).join("")}</select></label><label>Speaking<select data-field="speakingActivityId"><option value="">None</option>${speakingOptions.map(s=>`<option value="${s.id}" ${s.id===l.speakingActivityId?"selected":""}>${esc(s.title)}</option>`).join("")}</select></label><label>Activities / Notes<textarea data-field="notes" rows="3">${esc(l.notes)}</textarea></label><label>Resources / Links<textarea data-field="resources" rows="2" placeholder="One URL or resource per line">${esc(l.resources)}</textarea></label></div><button type="button" class="delete" data-delete>Delete lesson</button></article>`).join("")||`<p class="empty">No lessons yet. Add the first lesson.</p>`; list.querySelectorAll(".lesson-editor").forEach(el=>{const i=Number(el.dataset.index);el.querySelectorAll("[data-field]").forEach(f=>f.oninput=()=>lessons[i][f.dataset.field]=f.value);el.querySelector("[data-up]").onclick=()=>move(i,-1);el.querySelector("[data-down]").onclick=()=>move(i,1);el.querySelector("[data-delete]").onclick=()=>{lessons.splice(i,1);render();};});}
function move(i,d){const j=i+d;[lessons[i],lessons[j]]=[lessons[j],lessons[i]];render();}
q("#add-lesson").onclick=()=>{lessons.push({id:`lesson-${Date.now()}`,title:"",learningIntention:"",notes:"",vocabularySetId:"",speakingActivityId:"",resources:""});render();};
form.onsubmit=e=>e.preventDefault();q("#save").onclick=async()=>{if(!form.reportValidity())return;const english=q("#english").value.trim();if(!lessons.length){status.textContent="Add at least one lesson.";return;}const clean={id:unit?.id||makeId(`${yearLabel(q("#year").value)}-${english}`),yearLevel:Number(q("#year").value),englishTitle:english,chineseTitle:q("#chinese").value.trim(),lessons:lessons.map((l,i)=>({...l,id:l.id||`lesson-${i+1}`}))};status.textContent="Saving…";await saveUnit(clean);location.href=`view.html?unit=${encodeURIComponent(clean.id)}`;};render();
